### ISSUE TITLE
Create a proper API

### ISSUE THREAD

**Issue by spacekookie** [IGBC/L-CAD#13]
Currently the functions of the engines are kinda naked and exposed to the outside.

We need to change this so that inner functions are abstracted away and  provide an easier to use API.

This must include functions for:
- Creating Gates
- Creating connections
- Probing states (for connections and gates)
- Overriding values (for connections and gates)
- Stepping through the simulation

**Comment by IGBC** [comment]
implemented - mostly, 
project is not currently in a state to be interfaced with other modules / applications.

Closing
